resources:
  - name: git-repo
    source:
      branch: master
      private_key: {{github-private-key}}
      uri: git@github.com:trussworks/brainsik-ott-concourse-ci.git
    type: git

  - name: deb-package
    type: semver
    source:
      driver: s3
      bucket: truss-github-brainsik-ott-concourse-ci
      key: deb-package
      access_key_id: {{aws-access-key-id}}
      secret_access_key: {{aws-secret-access-key}}
      region_name: us-west-2

  - name: packed-ami
    type: semver
    source:
      driver: s3
      bucket: truss-github-brainsik-ott-concourse-ci
      key: packed-ami
      access_key_id: {{aws-access-key-id}}
      secret_access_key: {{aws-secret-access-key}}
      region_name: us-west-2

jobs:
  - name: unit-test
    plan:
      - get: git-repo
        trigger: true
      - task: task
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: python
              tag: "2"
          run:
            path: /bin/true

  - name: package-code
    plan:
      - get: git-repo
        passed:
          - unit-test
        trigger: true
      - put: deb-package
        params: {bump: minor}
      - task: task
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: python
              tag: "2"
          run:
            path: /bin/true

  - name: pack-ami
    plan:
      - get: git-repo
        passed:
          - package-code
        trigger: true
      - get: deb-package
        passed:
          - package-code
        trigger: true
      - put: packed-ami
        params: {bump: minor}
      - task: task
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: python
              tag: "2"
          run:
            path: /bin/true

  - name: deploy-staging
    plan:
      - get: git-repo
        passed:
          - pack-ami
        trigger: true
      - get: packed-ami
        passed:
          - pack-ami
        trigger: true
      - task: task
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: python
              tag: "2"
          run:
            path: /bin/true

  - name: test-staging
    plan:
      - get: git-repo
        passed:
          - deploy-staging
        trigger: true
      - get: packed-ami
        passed:
          - deploy-staging
        trigger: true
      - task: task
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: python
              tag: "2"
          run:
            path: /bin/true

  - name: promote-live
    plan:
      - get: git-repo
        passed:
          - test-staging
        trigger: true
      - get: packed-ami
        passed:
          - test-staging
        trigger: true
      - task: task
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: python
              tag: "2"
          run:
            path: /bin/true

  - name: test-live
    plan:
      - get: git-repo
        passed:
          - promote-live
        trigger: true
      - get: packed-ami
        passed:
          - promote-live
        trigger: true
      - task: task
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: python
              tag: "2"
          run:
            path: /bin/true
